### ISSUE TITLE
Does not work on Gentoo

### ISSUE THREAD

**Issue by grepwood** [aws-ew-dev/ElasticWolf#109]
Gentoo does not have a public xulrunner binary, so Firefox has to be used.
See 511ca29bfeff92d34474a175cdaf66235b2f4884 for a fix

**Comment by john-aws** [comment]
Hi, please note that the ElasticWolf GitHub repo is no longer under active maintenance. Thank you for the changes - we will review them for potential inclusion in the AWS-supported successor at the [AWS ElasticWolf Client Console page](https://aws.amazon.com/developertools/9313598265692691).
