### ISSUE TITLE
An unknown error occurred, please check connectivity and/or try to increase HTTTP timeout

### ISSUE THREAD

**Issue by CloudSpark** [aws-ew-dev/ElasticWolf#111]
Hello. I am trying to use the ElasticWolf client for Windows v. 5.1.6
I am receiving the above error.
Could I have configured the user incorrectly?  I did not see any documentation on how to initially configure the client.
I entered my credentials into the Credentials section and cannot get any further.

Thanks

**Comment by john-aws** [comment]
Hi, to add a new set of credentials, navigate to the Credentials pane, click Add from the toolbar, and then provide the following information:

- Name e.g. "cloudspark-admin"
- AWS Access Key e.g. "AKIAxxxxxxxx"
- AWS Secret Access Key e.g. "mPjjwfiuexxxxxxxxxx"
- Select a default endpoint of us-east-1

If you are still having issues then please verify that another AWS client application, such as the awscli, works on your computer with the same set of credentials. If that still does not help to resolve the issues then please enable debug logging in ElasticWolf (Preferences | Enable debug output, Preferences | Debug log to file), re-run your test, and email the elasticwolf.log file to us at the email address below. You should find elasticwolf.log in your home folder (e.g. c:\users\james).

For continued support, please contact us at aws-ew-dev@amazon.com. Thanks.
