### ISSUE TITLE
Only certain instances are shown

### ISSUE THREAD

**Issue by jypsilantis** [aws-ew-dev/ElasticWolf#112]

**Comment by jypsilantis** [comment]
Further to my earlier post, it appears that ALL menu items under "EC2 Networking" are not operating correctly. I set up an elastic IP vi at the web console and it too does not appear in ElasticWolf's lists.

**Comment by john-aws** [comment]
Hi, hope that you were able to resolve your issue.

Also, please note that this project is no longer actively maintained at GitHub. Please visit the official [ElasticWolf](https://aws.amazon.com/tools/aws-elasticwolf-client-console/) page at AWS for more.
