### ISSUE TITLE
cross account access

### ISSUE THREAD

**Issue by mjsprojects** [aws-ew-dev/ElasticWolf#114]
Hi,

To make management of multiple AWS account easier to manage we are using the cross-account-access feature of AWS.

This work well using aws-vault and temporary account credentials to gain access via the main account using the awscli.

I can't figure out how to configure ElasticWolf for this functionality though.

For example I might do 

aws-vault profile dev -- aws ec2 describe-instances

which would use the credentials configured on my "ops" profile to jump to the "dev" account by populating environment variables before calling awscli.

my ~/.aws/conf might look like this

[profile ops]
color    = auto
output    = json
region    = ap-southeast-2

[profile dev]
color      = auto
output      = json
region      = ap-southeast-2
role_arn     = arn:aws:iam::XXXXXXXXXXXX:role/cross-account-access
source_profile = ops

Is there a way to configure ElasticWolf to do something similar?

If not I might explore implementing this as a feature.

Thanks

**Comment by john-aws** [comment]
Hi, ElasticWolf does not natively support credentials supplied by AWS_xx environment variables or awscli profiles. The closest option is that ElasticWolf supports credentials supplied on the command line as:

```
-key xxx
-secret yyy
-token zzz
```

So it might be possible to use aws-vault to populate environment variables and then to provide those as command line options to ElasticWolf, something like:

`aws-vault profile dev -- ElasticWolf -key $AWS_ACCESS_KEY_ID etc.`

This is obviously a little cumbersome with all 3 AWS_xxx variables. It could be beneficial to enhance ElasticWolf, for example to support a `-env` command line option that tells ElasticWolf that credentials are in the AWS_xxx environment variables, then you could simply run:

`aws-vault profile dev -- ElasticWolf -env`

**Comment by john-aws** [comment]
ElasticWolf has been deprecated for some time, so all open issues are being closed.
