### ISSUE TITLE
How do I validate a URL

### ISSUE THREAD

**Issue by calston** [aws-ew-dev/ElasticWolf#115]
```
          case 'url':
             rc.values[i] = obj.value;
             if (obj.value && !/^https?:\/\/[0-9a-zA-Z-_\.]+$/.test(obj.value)) {
                 alert("The URL is not formatted properly");
                 return false;
             }
             break;
```

Really? 

![image](https://user-images.githubusercontent.com/1044161/48765158-46c22180-ecba-11e8-9cf2-2cde45821d51.png)

**Comment by john-aws** [comment]
The regular expression in this case does not support a trailing forward slash, so you would enter: `https://domain.com` rather than `https://domain.com/`.

**Comment by calston** [comment]
Well this argument is pointless since this is a dead project but a trailing forward slash is a perfectly valid URL, but the problem is more that this doesn't match a trailing / it matches any / after the domain so you can't have an endpoint on some other path than the root. eg /api if you're not actually using AWS.

**Comment by john-aws** [comment]
More flexibility in the URL seems like a very reasonable request. It might actually be simplest to modify the regex to https?:\/\/.+$

You should be able to make that change locally. We will add it to the next update of ElasticWolf, though I have no estimate right now for when that might be available.

**Comment by john-aws** [comment]
ElasticWolf has been deprecated for some time, so all open issues are being closed.
