### ISSUE TITLE
Cannot change active VPC

### ISSUE THREAD

**Issue by mikerj1** [aws-ew-dev/ElasticWolf#116]
I can't seem to find a way to change what VPC is being operated upon.  I can see the VPCs in the VPC menu, but when I go to EC2 Networking, only the default VPC is considered.  

Using version 5.1.7 on Mac.  Thanks

**Comment by john-aws** [comment]
The `EC2 Networking` section relates to EC2-Classic only, so it will not show EC2 instance that are in VPCs. All VPC-related resources appear under `VPC: Virtual Private Cloud`.

**Comment by john-aws** [comment]
Hi @mikerj1, please re-open with additional information if this did not resolve your issue Thanks.
