### ISSUE TITLE
The CloudFormation template written in YAML is not displayed

### ISSUE THREAD

**Issue by Gurpr33tS1ngh** [aws-ew-dev/ElasticWolf#117]
The CloudFormation template written in YAML when deployed does not displays the template in the "Template" section of the stack but if the template is written in JSON, the template is visible.

**Comment by john-aws** [comment]
Hi, please note that this project is no longer actively maintained. For the latest, AWS-supported version of ElasticWolf, please visit the [AWS ElasticWolf Client Console page](https://aws.amazon.com/tools/aws-elasticwolf-client-console/).
